"""Persisted identity and status vocabulary; transitions arrive in Phase 9."""

from enum import StrEnum


class ScenarioType(StrEnum):
    GREENFIELD = "GREENFIELD"
    BROWNFIELD = "BROWNFIELD"
    AMBIGUOUS = "AMBIGUOUS"


class WorkflowStatus(StrEnum):
    CREATED = "CREATED"
    RUNNING = "RUNNING"
    WAITING_FOR_CLARIFICATION = "WAITING_FOR_CLARIFICATION"
    WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL"
    REPLANNING = "REPLANNING"
    SAFE_STOPPED = "SAFE_STOPPED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class StageStatus(StrEnum):
    PENDING = "PENDING"
    BLOCKED = "BLOCKED"
    READY = "READY"
    RUNNING = "RUNNING"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    RETRY_PENDING = "RETRY_PENDING"
    FALLBACK_RUNNING = "FALLBACK_RUNNING"
    ROLLED_BACK = "ROLLED_BACK"
    STALE = "STALE"
    SKIPPED = "SKIPPED"
    SAFE_STOPPED = "SAFE_STOPPED"
    CANCELLED = "CANCELLED"
